# Author: Marc Ty

# Github actions template for Docker CI pipeline,
# this pipeline works for any docker container that needs
# to be built, tested, and pushed into the docker registry.

# For test compatibility, create a new file tests.sh 
# in the same directory as the Dockerfile. 
# Then use the bash file to add script test execution.

# The directory of the Dockerfile must also

# Change items in square brackets before use!
name: [NAME OF WORKFLOW]

on:
  workflow_dispatch:  # Enables manual triggering on workflows, remove to prevent.
  schedule:
    - cron: '45 13 * * *'
  push:
    branches: ["[THE BRANCH TO WATCH FOR]"]
    paths:
      - '[DIRECTORY IN REPO TO WATCH]/**'
    tags: ['v*.*.*']
  pull_request:
    branches: ["[THE BRANCH TO WATCH FOR]"]
    paths:
      - '[DIRECTORY IN REPO TO WATCH]/**'

env:
  # Set registry to Github Container Registry
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  NAME: [NAME OF IMAGE]

jobs:
  docker-build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set repository name to lowercase
        id: repo
        run: echo "repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image from Dockerfile
        run: docker build --tag ${{ env.REGISTRY }}/${{ env.repo_name }}/${{ env.NAME }}:latest ./[DIRECTORY OF DOCKERFILE]

      - name: Run tests in Docker container
        id: run-tests
        run: docker run --rm ${{ env.REGISTRY }}/${{ env.repo_name }}/${{ env.NAME }}:latest bash ./tests.sh

      - name: Handle test results
        if: steps.run-tests.outcome == 'failure'
        run: echo "The tests failed. Please check the logs for details."

      - name: Login to GitHub Container Registry
        if: steps.run-tests.outcome == 'success'
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image to Registry
        if: steps.run-tests.outcome == 'success'
        run: docker push ${{ env.REGISTRY }}/${{ env.repo_name }}/${{ env.NAME }}:latest
