# Author: Marc Ty

# Github actions template for Docker ci pipeline,
# this pipeline works for any docker container that needs
# to be built, tested and pushed into docker registry.

# For test compatibility create a new file tests.sh 
# in the same directory as the Dockerfile. 
# Then use the bash file to add script test execution.

# Change items in square bracket before use!
name: docker-react-vite

on:
  workflow_dispatch:  # Enables manual triggering on workflows, remove to prevent.
  schedule:
    - cron: '45 13 * * *'
  push:
    branches: ["Main"]
    paths:
      - 'client-app/**'
    tags: ['v*.*.*']
  pull_request:
    types: open
    branches: ["Main"]

env:
  # Set registry to Github Container Registry
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  NAME: react-vite-tel-interface

jobs:
  build-image-from-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Set repository name to lowercase
        id: repo
        run: echo "repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image from Dockerfile
        run: docker build --tag ${{ env.REGISTRY }}/${{ env.repo_name }}:test:latest ./client-app

  run-tests-in-bash:
    runs-on: ubuntu-latest
    needs: build-image-from-dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests in Docker container
        id: run-tests
        run: docker run --rm ${{ env.REGISTRY }}/${{ env.repo_name }}:test:latest ./tests.sh

      - name: Handle test results
        if: steps.run-tests.outcome == 'failure'
        run: echo "The tests failed. Please check the logs for details."

  push-image-as-pkg-to-container-registry:
    runs-on: ubuntu-latest
    needs: run-tests-in-bash
    if: github.event_name != 'pull_request' && needs.test.outputs.run-tests == 'success'
    steps:
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image to Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.repo_name }}:test:latest
